version: '4'

services:

    symfony: &symfony-template
      image: ${COMPOSE_PROJECT_NAME}-symfony:latest
      build:
        context: .
        args:
          BUILD_ARGUMENT_ENV: dev
          HOST_UID: ${HOST_UID}
          HOST_GID: ${HOST_GID}
          XDEBUG_CONFIG: ${XDEBUG_CONFIG}
        dockerfile: docker/php/Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}-symfony
      ports:
        - "${WEB_PORT_HTTP}:80"
        - "${WEB_PORT_SSL}:443"
      volumes:
        - ./:/var/www/html:cached
      depends_on:
        - mysql
        - rabbitmq
      networks:
        - symfony

    ### Cron tasks, RabbitMQ consumers
    supervisord:
      <<: *symfony-template
      container_name: ${COMPOSE_PROJECT_NAME}-supervisord
      expose: []
      command: ["/usr/bin/supervisord"]
      ports:
        - "${SV_PORT_HTTP}:80"
        - "${SV_PORT_SSL}:443"

    mysql:
      image: mysql:8.0
      platform: linux/x86_64
      container_name: ${COMPOSE_PROJECT_NAME}-mysql
      command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=${INNODB_USE_NATIVE_AIO:-1}
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#      build:
#        dockerfile: docker/mysql/Dockerfile
      ports:
        - "3306:3306"
      volumes:
        - ./var/mysql-data:/var/lib/mysql:delegated
        - ./docker/dev/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      networks:
        - symfony

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: ${COMPOSE_PROJECT_NAME}-pma
      links:
        - mysql
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
        restart: unless-stopped
      ports:
        - ${PMA_PORT}:80
      networks:
        - symfony

    rabbitmq:
      image: ${COMPOSE_PROJECT_NAME}-rabbitmq
      build:
        context: ./docker/rabbitmq/
        dockerfile: ./Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}-rabbitmq
      environment:
        RABBITMQ_ERLANG_COOKIE: 7ead507151fc4461b9f45c1161384a04
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
        RABBITMQ_DEFAULT_VHOST: /
      ports:
        - "15672:15672"
      volumes:
        - ./var/rabbitmq:/var/lib/rabbitmq:delegated
      networks:
        - symfony

    ###> symfony/mailer ###
    mailer:
      image: axllent/mailpit
      ports:
        - "1025"
        - "8025"
      environment:
        MP_SMTP_AUTH_ACCEPT_ANY: 1
        MP_SMTP_AUTH_ALLOW_INSECURE: 1
    ###< symfony/mailer ###


networks:
  symfony:
    driver: bridge

